# =============================================================
# ASCENDERSMC-UNIVERSAL-INSTALLER 0.8.4
# Proyecto independiente de ASCENDERSMC-LAUNCHER.
# La información de distribución se adaptó del launcher 0.8.8.
# =============================================================

# Directorio base del Installer. Si se omite, en Windows se usa:
# %APPDATA%\ASCENDERSMC\UniversalInstaller
install.base.dir=

server.host=ascendersmc.online
server.port=25565

# COBBLEWORLD
profile.cobbleworld.modpack.release.api=https://api.github.com/repos/PlatanoV3rde/ASCENDERSMC-MODPACK-DESCARGA/releases/latest
profile.cobbleworld.modpack.asset.name=
profile.cobbleworld.modpack.asset.prefix=ASCENDERSMC-Modpack
profile.cobbleworld.minecraft.version=1.21.1
profile.cobbleworld.neoforge.version=21.1.248
profile.cobbleworld.resourcepack.release.api=https://api.github.com/repos/PlatanoV3rde/ASCENDERSMC-RESOURCEPACK-COBBLEMON/releases/tags/resourcepack
profile.cobbleworld.resourcepack.asset.name=ASCENDERSMC_COBBLEMON.zip


# PIXELMON
profile.pixelmon.modpack.release.api=https://api.github.com/repos/PlatanoV3rde/ASCENDERSMC-MODPACK-DESCARGA-PIXELMON/releases/latest
profile.pixelmon.modpack.asset.name=
profile.pixelmon.modpack.asset.prefix=ASCENDERSMC-Modpack-Pixelmon
profile.pixelmon.minecraft.version=1.21.1
profile.pixelmon.neoforge.version=21.1.248
profile.pixelmon.resourcepack.release.api=https://api.github.com/repos/PlatanoV3rde/ASCENDERSMC-RESOURCEPACK-PIXELMON/releases/tags/resourcepack
profile.pixelmon.resourcepack.asset.name=ASCENDERSMC_RESOURCEPACK.zip


# Primera ejecución del perfil aislado.
first.run.gui.scale=2
server.resourcepack.mode=NO

# Debug completo del flujo del instalador.
debug.enabled=true

# ==========================================================
# AUTO-ACTUALIZACIÓN DEL INSTALLER
# ==========================================================
update.enabled=true
update.release.api=https://api.github.com/repos/PlatanoV3rde/ASCENDERSMC-UNIVERSAL-INSTALLER/releases/latest
update.asset.name=ASCENDERSMC-UNIVERSAL-INSTALLER.jar
update.checksum.asset.name=SHA256SUMS.txt
